apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-operator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator-clusterrole
rules:
# Права для работы с кастомными ресурсами MySQL
- apiGroups: ["otus.homework"]
  resources: ["mysqls", "mysqls/status", "mysqls/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
# Права для создания/удаления Deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
# Права для создания/удаления Services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
# Права для создания/удаления PersistentVolumeClaims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  
# Права для работы с PersistentVolumes (только чтение, создание PV обычно автоматическое)
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
  
# Права для работы с Pods (для мониторинга состояния)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
  
# Права для работы с событиями (для логирования)
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mysql-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: mysql-operator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: mysql-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io